### ISSUE TITLE
Corregir nombre de los métodos

### ISSUE THREAD

**Issue by roadev** [ico1293/Convertidor#1]
Corregir nombre de los métodos, debe usarse la misma "práctica" que se usa en los objetos y variables.
Sólo las clases inician con mayúsculas.

https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html

**Comment by ico1293** [comment]
Ya lo corregí no joda ¬¬

**Comment by roadev** [comment]
Y se escribe:
Fixed (o arreglado con: ): 
d249834025fccd5042da095553a2b192173ab83c
(colocas el id del commit)

**Comment by ico1293** [comment]
Fixed with
https://github.com/ico1293/Convertidor/commit/3bafb6868d423201592ccb706c7dd4e48a61fc9d
